### ISSUE TITLE
fix function clone in utils.ts

### ISSUE THREAD

**Issue by antonRoyenko** [grammyjs/conversations#28] opened 2022-08-11 09:30 UTC
If I had in context property with BigInt, for example user with telegramId I have issue `Do not know how to serialize a BigInt` in line const string = JSON.stringify(arg);
![Screenshot 2022-08-11 at 12 30 08](https://user-images.githubusercontent.com/37601845/184104581-60f6c887-9fb6-46d3-a905-20d08320c9e4.png)

**Comment by zdev-online** [comment] 2022-09-20 00:45
### Raise the topic 

This is an important problem that needs to be solved, because we are talking about Telegram ID

**Comment by KnorpelSenf** [comment] 2022-09-20 05:52
For bots, Telegram ID is of type `number` not `bigint`. This is an important problem nonetheless, are you willing to look into fixing this?

**Comment by antonRoyenko** [comment] 2022-09-20 13:12
Yes, I could fix it during this week

**Comment by KnorpelSenf** [comment] 2022-09-20 14:47
Thank you so much, looking forward to your changes!

**Comment by KnorpelSenf** [comment] 2022-09-23 09:17
I have evaluated a variety of different approaches now, including [devalue](https://github.com/Rich-Harris/devalue), [lave](https://github.com/jed/lave), [arson](https://github.com/benjamn/arson), [node-tosource](https://github.com/marcello3d/node-tosource), [serialize-javascript](https://github.com/yahoo/serialize-javascript), [jsesc](https://github.com/mathiasbynens/jsesc), [superjson](https://github.com/blitz-js/superjson), and a few custom implementations, and I have concluded that arson provides the best starting point for creating the solution to our problem. You may be interested in following https://github.com/benjamn/arson/issues/16, but of course nothing is stopping you from simply rolling your own solution :)

**Comment by KnorpelSenf** [comment] 2022-09-25 17:06
I now created a tool which can be used in this plugin. It is able to solve almost every problem we encountered. It is called `oson` on `/x` and `o-son` on npm. The repo is here: https://github.com/KnorpelSenf/oson

**Comment by KnorpelSenf** [comment] 2022-09-27 12:13
@antonRoyenko are you still interested in working on this? :)

**Comment by snussik** [comment] 2022-10-23 18:36
The bug is still here. With this structure of object I get the same `Do not know how to serialize a BigInt` error:
```bash
{
  instance: Fluent {
    options: {},
    bundles: Set(2) { [FluentBundle], [FluentBundle] },
    warningHandler: LoggingWarningHandler { options: {}, writeLog: [Function: warn] },
    defaultBundle: FluentBundle {
      _terms: Map(0) {},
      _messages: [Map],
      locales: [Array],
      _functions: [Object],
      _useIsolating: false,
      _transform: [Function: transform],
      _intls: Map(0) {}
    }
  },
  renegotiateLocale: [AsyncFunction: negotiateLocale],
  useLocale: [Function: useLocale]
}
```

**Comment by KnorpelSenf** [comment] 2022-10-23 21:55
> the problem in utils can be simply solved by lodash.cloneDeep()

This is false. This will not help with bigint support in any way.

> So this error moves deeper.

I do not understand what you mean. The problem is already solved with the library I linked above. As soon as we integrate it into this plugin, everything will be fixed.

**Comment by snussik** [comment] 2022-10-24 08:27
@KnorpelSenf  in my case this fix helped (btw, I store object of User type in my ctx):
```js
export function clone<T>(arg: T) {
 if (arg === undefined) return undefined;
 return _.cloneDeep(arg)
}
```
I've tried to use your [oson](https://github.com/KnorpelSenf/oson) lib (for node), but in my case I got empty array [ ].

> I do not understand what you mean.

I mean that grammy was developed with assumption that telegram's ids can be just of number type [as it's written here](https://github.com/grammyjs/types/blob/main/manage.d.ts#L28). That's why  you can meet `JSON.stringify(ctx, session and so on)`  in [grammy's code base](https://github.com/grammyjs/storages/search?q=JSON.stringify%28&type=) . 

So it doesn't matter that you solve the problem in conversation module. If you have a bigint type in the object, the error will be raised in some other part of code. In order to fix it completely the type should be changed to bigint in @grammyjs/types and all JSON.stringify() occurrences changed to some other method.

In my case I had to change my type for telegram ids from `BigInt` to `number` in code and database schema. That helped.

**Comment by KnorpelSenf** [comment] 2022-10-24 08:42
This cloning function can only work with some storage adapters. It is a flawed approach.

Number values are implemented exactly according to the specification. This assumption is valid and it is never going to change.

If you use bigint, then you're doing something that's unrelated to bots. For example, Telegram user bots need this data type. Such values are never going to be processed by grammY.

Supporting bigint values is only a problem when it comes to storing arbitrary data. This is what the conversations plugin does internally. Note that it's the only grammY plugin that needs to store arbitrary data. That's why this is the only plugin that's affected by this issue. Using oson in this plugin will allow us to convert arbitrary data into a format that can be safely passed to `JSON.stringify`. Thus, the issue will be fixed for all storage adapters.

**Comment by Madnex** [comment] 2022-10-31 20:28
Is there an update on this? I'm encountering the same issue. What's the best workaround for now? I'm using prisma + postgres and BigInt for the telegramID...

**Comment by KnorpelSenf** [comment] 2022-11-05 15:22
As a workaround, you can convert bigints to string and back until oson is integrated into this plugin.

**Closed** 2022-11-26 20:18 UTC
