### ISSUE TITLE
Bot freezes and becomes unresponsive after user reply in conversation

### ISSUE THREAD

**Issue by MahoushoujoMadoka** [grammyjs/conversations#125] opened 2024-11-10 11:09 UTC
Below is the relevant code snippet:

```javascript
bot.use(session({
  initial: initialSession,
  storage: new FileAdapter({
      dirName: 'sessions',
    }),
  }))
  
bot.use(conversations())

const myConversation= async (conversation, ctx) => {
  const { message_id } = await ctx.reply('Please enter the address');
  const { msg } = await conversation.waitFor('message');
  console.log(msg);
}

```
### Problem
After the bot enters this conversation, it successfully sends a prompt message to the user with `ctx.reply('Please enter the address')`. However, as soon as the user replies, the bot freezes completely:

The `console.log(msg)` line is never executed, so the message is never logged.
The entire bot becomes unresponsive to any further inputs or commands.
The only way to restore functionality is by deleting the cached session and restarting the project. Simply restarting without clearing the session doesn’t solve the problem, as it replays the last session and continues to freeze.

This might be my own issue, but I've spent considerable time trying to debug without success. Any insights or suggestions on what might be causing this issue would be greatly appreciated.

### Version Information
- **grammy**: `^1.31.0`
- **@grammyjs/conversations**: `^1.2.0`
- **bun**: `^1.1.34`

**Comment by KnorpelSenf** [comment] 2024-11-10 11:22
Which version of the plugin do you use?

This typically only happens on v1.x when you call `conversation.external` and pass a callback that again performs API calls. I cannot reproduce this with the above code alone.

**Comment by MahoushoujoMadoka** [comment] 2024-11-10 11:25
Thank you for looking into this issue! Here’s the version information for the plugins I’m currently using:

- **grammy**: `^1.31.0`
- **@grammyjs/conversations**: `^1.2.0`

**Comment by KnorpelSenf** [comment] 2024-11-10 11:30
Can you reproduce the same issue with Node.js?

**Comment by MahoushoujoMadoka** [comment] 2024-11-10 11:33
Yes, I encountered the same issue with Node.js as well.

**Comment by KnorpelSenf** [comment] 2024-11-10 11:39
The above code works flawlessly on my machine.

**Comment by KnorpelSenf** [comment] 2024-11-10 11:41
Here is the full code I used, just to make sure you did not introduce a bug somewhere in the code you did not share (such as in `initialSession`. Copy the following code, paste your token, and run it:

```ts
import { Bot, session } from "grammy";
import { conversations, createConversation } from "@grammyjs/conversations";
import { FileAdapter } from "@grammyjs/storage-file";

const bot = new Bot("");

function initialSession() {
  return {};
}

bot.use(session({
  initial: initialSession,
  storage: new FileAdapter({
    dirName: "sessions",
  }),
}));

bot.use(conversations());

const myConversation = async (conversation, ctx) => {
  const { message_id } = await ctx.reply("Please enter the address");
  const { msg } = await conversation.waitFor("message");
  console.log(msg);
};
bot.use(createConversation(myConversation));

bot.command("start", (ctx) => ctx.conversation.enter("myConversation"));

bot.start();
```

**Comment by MahoushoujoMadoka** [comment] 2024-11-10 13:16
Thank you for your guidance. I was able to reproduce the issue using the following code:

```javascript
import { Bot, InlineKeyboard, session } from "grammy";
import { conversations, createConversation } from "@grammyjs/conversations";
import { FileAdapter } from "@grammyjs/storage-file";

const bot = new Bot("");
export const extendContext = async (ctx, next) => {
  ctx.safeAnswer = async (...args) => {
    if (!ctx.callbackQuery) {
      return false;
    }
    return await ctx.answerCallbackQuery(...args).catch(() => false);
  };

  ctx.replyAndSafeAnswer = async (...args) => {
    await ctx.safeAnswer();
    return await ctx.reply(...args);
  };
  await next();
};

const initialSession = () => {
  return {};
};

bot.use(
  session({
    initial: initialSession,
    storage: new FileAdapter({
      dirName: "sessions",
    }),
  })
);
bot.use(conversations());
bot.use(extendContext);

const myConversation = async (conversation, ctx) => {
  const { message_id } = await ctx.replyAndSafeAnswer("Please enter the address");
  const { msg } = await conversation.waitFor("message");
  console.log(msg);
  await ctx.replyAndSafeAnswer("Done");
};
bot.use(createConversation(myConversation));

bot.command("start", async (ctx) => {
  ctx.reply("hi", {
    reply_markup: new InlineKeyboard().text("setAddress", "setAddress"),
  });
});
bot.callbackQuery("setAddress", async (ctx) => {
  await ctx.conversation.enter("myConversation");
});
bot.start();
```
I noticed that the issue only occurs when entering the conversation via the inline keyboard button (setAddress). If I trigger the conversation directly through a command, it works as expected. Let me know if you need any further details. Thank you for your assistance!

**Comment by KnorpelSenf** [comment] 2024-11-10 14:14
Ah well. That explains a lot.

There is a short and a long explanation as to why this happens. There is a hacky fix for v1 and a clean way to fix this for the soon-to-be-released v2.

Let's start with the short explanation and the clean solution, and then I'll give you the long explanation and the hacky fix.

### The Short Explanation

The custom function that you install on the context object is not supported by conversations v1. It can detect that there is a function, but it does not know how to handle it. The plugin then tries to come up with a fix, but ends up calling the wrong function internally. This confuses the plugin so much that it basically waits forever.

The runtime sees that no code is running anymore and garbage-collects the entire process. This is what you observe as a terminating process.

### The Clean Fix

Conversations v1 are a cool abstraction with a poor implementation. I rewrote the entire plugin from scratch and these things are all fixed now. It will be released in the coming time after the documentation is completed and has been translated to all 5 other languages.

The proper fix is to upgrade to v2. You can install it from GitHub.

```sh
npm install github:grammyjs/conversations
```

A number of things have changed, and the migration guide is not done yet, but the README as well as https://github.com/grammyjs/website/pull/1147#issuecomment-2466258345 with its deployment preview should give you some insight.

Basically, the only thing you have to change is to use

```ts
bot.use(createConversation(myConversation, {
  plugins: [extendContext]
}));
```

I have tried your code and this fixes the issue.

Check out https://t.me/grammyjs/277882, too.

### The Long Explanation

As you can read in the v2 docs, conversations are replay engines. This is true for both versions of the plugin. However, v1 tried to directly persist the context objects themselves in a file. You installed a function. Functions cannot be persisted. In an attempt to fix this, the v1 plugin delegates the function call to the new incoming context object. However, this causes the replay logs to deviate from the the actual behaviour of the conversation builder function. There is a weird bug in the v1 plugin that it cannot detect this, so it tries to wait for the result of an API call that has never been recorded. As a result, it waits for data that does not exist, which is like doing `await new Promise(() => {})`—it garbage-collects the current stack and hence terminates the runtime. This is very hard to fix with the implementation of v1. The underlying flaw is that context objects are reused across replays, and that should just not be done. (That's why v2 does not do it.)

### The Hacky Fix With v1

I do not feel like expanding on why this works, but it does. (I tested it, too.)

```ts
// Replace
const { message_id } = await ctx.replyAndSafeAnswer("Please enter the address");
// with
if (!conversation._isReplaying) {
  const { message_id } = await ctx.replyAndSafeAnswer("Please enter the address");
}
```

**Closed by KnorpelSenf** 2024-11-10 14:14 UTC
