### ISSUE TITLE
Crash only in 1 conversation

### ISSUE THREAD

**Issue by dimashpt** [grammyjs/conversations#85] opened 2023-08-15 16:45 UTC
I don’t know how to describe the issue, because it's confusing to me.
I have 2 convos, it's all working good. But, when i add 1 more, enter the convo, and reply, i immediatelly get an error that says in session:

```json
...
"error_code",
400,
"description",
"Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message",
"answerCallbackQuery",
...
```

Refer to [my commit](https://github.com/sastra-koding/telebot-absensi/commit/36ea3b99b37299474979cc2a22966a6cc302c7bb)

I'm using TS with nodemon server, after the error, i didn’t get any response and the server says
`clean exit - waiting for changes before restart`

you can also see my code [here](https://github.com/sastra-koding/telebot-absensi)

Did i do any mistakes?
Thanks

**Comment by dimashpt** [comment] 2023-08-15 17:25
I finally found out. This is related with grammy/menu. I have to do this:
```
const menu = new MenuTemplate<MainContext>(async (ctx) => {
  // I have to mock async function and return the string to make it works?
  const mock = () =>
    new Promise<string>((resolve) => {
      setTimeout(() => {
        resolve('Menu Presensi');
      }, 100);
    });
  const data = await mock();

  return data;
});
```

This is weird behaviour when i don't really need the promise.
Any explanations? am i missing something?

**Comment by KnorpelSenf** [comment] 2023-08-18 21:58
@EdJoPaTo do you know? It seems to be related to grammy-inline-menu?

**Comment by EdJoPaTo** [comment] 2023-08-21 09:38
it seems very unlikely that this is the root cause as the body function of a MenuTemplate is just the sendMessage or editMessage text… using async/await will just delay the same method call to a later point…

The code is basically identical to this: `const menu = new MenuTemplate<MainContext>('Menu Presensi');`

Also the error is hidden via grammy-inline-menu itself when editing the menu so this error happens sometimes but is [catched](https://github.com/EdJoPaTo/grammy-inline-menu/blob/aaedb6a2721215bfc56e540b80c5b9e0888e4128/source/send-menu.ts#L148).

I am not sure how conversations work and they might be incompatible with the basic ideas of the grammy-inline-menu library… but in general it works with context filters.

Currently I dont have another idea where the root cause may be…

**Comment by KnorpelSenf** [comment] 2023-10-02 11:40
I guess we cannot really do anything here. I will close this. @dimashpt feel free to reopen with a proper reproduction example of this problem if this is still an issue.

**Closed by KnorpelSenf** 2023-10-02 11:40 UTC
